go1com/util_core

es/Schema.php

Add field status on account_enrolment

GO1P-20583 Add field status on account_enrolment

---

MailTemplate.php
queue/Queue.php

GO1P-18610: As Admin I Can send bulk email/in-app notification to selected users from any report contains user field

GO1P-18610: As Admin I Can send bulk email/in-app notification to selected users from any report contains user field

---

collection/PortalCollectionConfiguration.php

Added a CONTENT_LOADER type to PortalCollectionConfiguration to be able to handle all content loader imports in an own collection.

GO1P-21602: Added a CONTENT_LOADER type 

---

queue/Queue.php

Adding a new queue for the content-import microservice to process imports.

GO1P-21844

---

MailTemplate.php
content-import/ContentImportComplete.php
contentImport/ContentImportComplete.php
queue/Queue.php
tests/contentImport/ContentImportCompleteTest.php

Updating to use new method for defining queue and adding notification type

GO1P-21848 updating notify templates and using new queue definition

---

contract/ServiceConsumeController.php

Code taken from go1com/util
https://github.com/go1com/util/blob/master/consume/ConsumeController.php#L59

GO1P-22910 Catch notify exception

---

dimensions/DimensionHelper.php
schema/mock/DimensionsMockTrait.php
tests/dimensions/DimensionsHelperTest.php

Adds a dimensions helper for use in the recommender micro service.

GO1P-26176

---

lo/LoSchema.php

Revert "GO1P-25184 Fixing slow queries with column origin_id"

---

lo/LoHelper.php
schema/mock/LoMockTrait.php
tests/lo/LoHelperTest.php

The change in format has been requested as it will be easier to index into ElasticSearch

GO1P-26987 Updated the attributes format as requested

---

lo/LoHelper.php
tests/UtilCoreTestCase.php
tests/lo/LoHelperTest.php

Revert "GO1P-26987 Updated to allow the dimension DB to be passed in"

---

lo/explore/LoExploreSchema.php

`elastic: Error 400 (Bad Request): Failed to parse mapping [lo]: No type specified for field [attributes] [type=mapper_parsing_exception]`

Fix es lo explore schema

---

dimensions/DimensionHelper.php
lo/LoHelper.php

GO1P-27457 Updated dimension and lo helpers to use the new format for dimension attributes

---

lo/explore/LoExploreSchema.php

This MR adds four new rating attributes to the schema.
download_speed, audio_visual_design, presentation_of_content, structure_navigation.
These ratings will be populated by the COPS team and used as part of giving learning objects an overall rating.

GO1P-31024

---

lo/LoAttributes.php
lo/PackageLicenseTypes.php

This will be used by LO as part of the new portal subscription type (where every user gets access)

Go1 p 33066

---

dimensions/DimensionType.php
edge/EdgeTypes.php
lo/LoAttributes.php
lo/LoTypes.php
lo/explore/LoExploreSchema.php

- add new playlist lo type
- add `roles, skill` to loAttribute , 
- add `Role&Skill` to dimensionType 
- update Role and skill attributes in loExploreSchema

GO1P-33716: add new playlist lo type, `roles, skill` to loAttribute , `Role&Skill` to dimensionType and update loExploreSchema

---

DB.php

Support _SLAVE for username + password, fully use utf8mb4 for DB

---

schema/UserSchema.php
schema/mock/UserMockTrait.php
tests/user/UserHelperTest.php

this is a uuid property that will only be filled on accounts (null for user) and will be equal to the user records uuid.

added relation from account to user

---

AccessChecker.php
tests/AccessCheckerTest.php

GO1P-36029: Helper check playerTokenIsVerified from the request

---

schema/EnrolmentSchema.php

Revert "Added lo_id indexed"

---

lo/LoAttributes.php
lo/explore/LoExploreSchema.php

Adding new constant for 'streamable' attribute

CM-243 Adding new constant for 'streamable' attribute

---

tests/QueueMockTrait.php

As per ticket https://go1web.atlassian.net/browse/PSE-999

PSE-999 Logging for RabbitMQ Errors in Enrolment Service

---

schema/PortalSchema.php

Iaam 343v2

---

composer.json

https://github.com/go1com/app/pull/70
https://code.go1.com.au/go1-core/go1-core/-/merge_requests/2345/diffs

Fixed dbal 2.13.8

---

composer.json

https://code.go1.com.au/domain-learning-activity/enrolment/-/blob/master/resources/composer.lock#L323-341

Upgrade to 2.12.1 minimum required by enrolment
